    - name: create folder /srv/gitlab
      file:
         path: /srv/gitlab
         state: directory
         mode: '0755'
         recurse: yes
      tags:
      - gitlab

    - name: "export GITLAB HOME in now bash"
      shell: "export GITLAB_HOME=/srv/gitlab"

    - name: Add GITLAB_HOME environment variable to /etc/profile
      lineinfile:
       path: /etc/profile
       line: 'export GITLAB_HOME=/srv/gitlab'
       create: yes
       insertafter: EOF
      tags:
      - gitlab


    - name: Create docker-compose.yml file
      copy:
        dest: /home/evgen/ansible/gitlab/docker-compose.yml
        content: |
          version: '3.6'
          services:
            gitlab:
              image: gitlab/gitlab-ce:latest
              container_name: gitlab
              restart: always
              hostname: 'zheksongitlab.com'
              environment:
                GITLAB_OMNIBUS_CONFIG: |
                  external_url 'http://zheksongitlab.com'
                  gitlab_rails['gitlab_shell_ssh_port'] = 2424
              ports:
                - '80:80'
                - '443:443'
                - '2424:22'
              volumes:
                - '/srv/gitlab/config:/etc/gitlab'
                - '/srv/gitlab/logs:/var/log/gitlab'
                - '/srv/gitlab/data:/var/opt/gitlab'
              shm_size: '256m'
      become_user: root
      tags:
      - gitlab

    - name: Deploy GitLab using Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/evgen/ansible/gitlab/
        state: present
      tags:
      - gitlab

#gitlab не пускал по ssh. Причина крылась в сервисе sshd , который ругался на права по ключ