- name: Install Exporter
  hosts: ALL
  gather_facts: yes
  become: yes
  roles:
        - grafana
  tags:
        - exporterStart
        - grafanaStart

- name: Install Prometheus
  hosts: one
  gather_facts: yes
  become: yes
  roles:
        - grafana
  tags:
        - prometheusStart
