- name: Запустить контейнер Node Exporter
  docker_container:
        name: node_exporter
        image: quay.io/prometheus/node-exporter:latest
        state: started
        restart_policy: always
        network_mode: host
        pid_mode: host
        volumes:
          - "/:/host:ro,rslave"
        command: "--path.rootfs=/host"
  tags:
     - exporterStart