    - name: update cache
      apt: 
        update_cache: yes

    - name: install ca-certificates and curl
      apt:
         name: "{{pakages_one}}"
         state: present
    
    - name: create folder /etc/apt/keyrings
      file:
         path: /etc/apt/keyrings
         state: directory
         mode: '0755'
         recurse: yes

    - name: "apt key"
      get_url:
          url: https://download.docker.com/linux/ubuntu/gpg
          dest: /etc/apt/keyrings/docker.asc

    - name: "apt source"
      apt_repository:
           repo:  "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
           state: present

    - name: update cache two
      apt: 
        update_cache: yes

    - name: install pakages_two
      apt:
         name: "{{pakages_two}}"
         state: present

    - name: Run hello-world container
      docker_container:
         name: hello-world
         image: hello-world
         state: started

    - name: docker groups
      user:
         name: evgen
         groups: docker
         append: yes
      
    - name: Install net-tools
      apt:
       name: net-tools
       state: present

    - name: Запустить контейнер Node Exporter
      docker_container:
        name: node_exporter
        image: quay.io/prometheus/node-exporter:latest
        state: started
        restart_policy: always
        network_mode: host
        pid_mode: host
        volumes:
          - "/:/host:ro,rslave"
        command: "--path.rootfs=/host"
